[tool.poetry]
name = "extremitypathfinder"
version = "2.7.2"
license = "MIT"
readme = "README.rst"
repository = "https://github.com/jannikmi/extremitypathfinder"
homepage = "https://extremitypathfinder.readthedocs.io/en/latest/"
documentation = "https://extremitypathfinder.readthedocs.io/en/latest/"
keywords = ["path-planning", "path-finding", "shortest-path", "visibility", "graph", "polygon", "grid", "map", "robotics", "navigation", "offline"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Education",
    "Topic :: Games/Entertainment"
]
description = "python package for fast shortest path computation on 2D polygon or grid maps"
authors = ["jannikmi <github@michelfe.it>"]
include = [
    "LICENSE",
    ".editorconfig",
    ".pre-commit-config.yaml",
    "CHANGELOG.rst",
    "CONTRIBUTING.rst",
    "Makefile",
    "README.rst",
    "tox.ini",
    "tests/*.py",
    "example.json",
]
#exclude = ["my_package/excluded.py"]

[tool.poetry.scripts]
extremitypathfinder = "extremitypathfinder.command_line:main"

[tool.poetry.dependencies]
python = ">=3.10,<4"
networkx = ">=3,<4"
numpy = [
    { version = ">=2.2,<3", python = "<3.14" },
    { version = ">=2.3.3,<3", python = ">=3.14" }
]
numba = [
    { version = ">=0.61.2,<1", python = "<3.14", optional = true },
    { version = ">=0.63,<1", python = ">=3.14", optional = true }
]
# Required for Numba's np.linalg.solve implementation.
scipy = [
    { version = ">=1.14.1,<2", python = "<3.14", optional = true },
    { version = ">=1.16.1,<2", python = ">=3.14", optional = true }
]

[tool.poetry.group.dev.dependencies]
pre-commit = "*"
pytest = "*"
tox = "*"

[tool.poetry.group.plot.dependencies]
# also required for runnin the tests
matplotlib = "*"

[tool.poetry.group.docs.dependencies]
Sphinx = "*"
sphinx-rtd-theme = "*"

[tool.poetry.group.plot]
optional = true

[tool.poetry.group.docs]
optional = true


[tool.poetry.extras]
numba = ["numba", "scipy"]

[build-system]
requires = ["poetry-core>=2,<3"]
build-backend = "poetry.core.masonry.api"

[tool.tox]
legacy_tox_ini = """
[tox]
minversion = 4
isolated_build = true
envlist =
    py{310,311,312,313,314}{,-numba}
    py{310,311,312,313,314}-minimum{,-numba}

[testenv]
package = wheel
extras =
    numba: numba
deps =
    pytest
    matplotlib
    minimum: networkx==3.0
    py310-minimum,py311-minimum,py312-minimum,py313-minimum: numpy==2.2.0
    py314-minimum: numpy==2.3.3
    py310-minimum-numba,py311-minimum-numba,py312-minimum-numba,py313-minimum-numba: numba==0.61.2
    py314-minimum-numba: numba==0.63.0
    py310-minimum-numba,py311-minimum-numba,py312-minimum-numba,py313-minimum-numba: scipy==1.14.1
    py314-minimum-numba: scipy==1.16.1
setenv =
    MPLBACKEND = Agg
    !numba: EXPECT_NUMBA = 0
    numba: EXPECT_NUMBA = 1
commands =
    python -m pip check
    python -m pytest {posargs}

[testenv:docs]
basepython = python3.12
extras =
deps =
    Sphinx
    sphinx-rtd-theme
    matplotlib
commands =
    sphinx-build -d "{envtmpdir}{/}doctree" docs "{toxworkdir}{/}docs_out" --color -b html
"""
